# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'ZDBlockHookDemo' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for ZDBlockHookDemo
  pod 'libffi-core'
  pod 'ZDBlockHook', :path => '../'
 
  target 'ZDBlockHookDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ZDBlockHookDemoUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
